version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wppool  
      WORDPRESS_DB_PASSWORD: wppool
      WORDPRESS_DB_NAME: wppool
      # our local dev environment
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
         /* development parameters */
          define('WP_CACHE', false);
          define('ENVIRONMENT', 'local');
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wppool
      MYSQL_USER: wppool
      MYSQL_PASSWORD: wppool
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

volumes:
  themes:
  plugins:
  db: